$('.owl-theme').owlCarousel({
    loop:true,
    margin:30,
    dots:false,
    nav:false,
    responsive:{
        0:{
            items:3
        },
        500:{
            items:3
        },
        700:{
            items:4
        },
        850:{
            items:5
        },
        1000:{
            items:6
        }
    }
})
